### ISSUE TITLE
Disable icons and no anti-aliasing on fonts

### ISSUE THREAD

**Issue by EddoWagt** [vinceliuice/grub2-themes#106]
Love these themes, but would like to remove the icons if possible. And for some reason my grub won't show any anti-aliasing (not only with these themes), can I fix that somehow?

**Comment by vinceliuice** [comment]
Grub does not support anti-aliasing

**Comment by vinceliuice** [comment]
If you don't like the icons you can just remove the icons folder, then it'll not show on the grub
