### ISSUE TITLE
Trying to configure 3440x1440 but grub is not changing

### ISSUE THREAD

**Issue by enoren5** [vinceliuice/grub2-themes#110]
I seemed to have run into one of the the known issues described in the `README.md`.

After entering the command line at grub, `vbeinfo` returns nothing. Entering `videoinfo` returns this: https://imgur.com/a/Ld4KgdD

Apparently my grub recognizes a max resolution of 1280x1024 meanwhile the  resolution for my monitor is 3840x1600 (although I understand and be willing to settle for the supported 3440x1440 which the app is designed to support).

The contents of `/etc/default/grub` (but specifically the line which says: `GRUB_GFXMODE`) I have set to: `=3440x1440x32`.

After making that change I saved to file and entered: `sudo grub-mkconfig -o /boot/grub/grub.cfg`.

I rebooted, held my breath, and surprise! Grub remained at 1024x768 and there was no fancy splash, just the ugly plain default appearance. Grub remains unchanged.

What am I missing? What could I try next?

**Comment by vinceliuice** [comment]
The highest supported resolution of your screen on grub is 1280x1024, no matter how high you set it, it’s useless, not supported

**Comment by enoren5** [comment]
Thank you @vinceliuice for the reply! 

Is there a way to override grub's setting and force 2560x1080 or 3440x1440 or even larger?

Even with the 1280x1024 limitation, am I able to still use the nice grub2 themes that you provide?

**Comment by vinceliuice** [comment]
I also don’t know how to solve it, maybe it has something to do with bios settings and graphics card driver
