### ISSUE TITLE
Can't install in Kali Linux 2020.4

### ISSUE THREAD

**Issue by iamsubingyawali** [vinceliuice/grub2-themes#111]
I am not being able to install this theme in Kali Linux 2020.4. I tried installing on boot directory too but it didn't work. It shows the default Kali grub theme in grub and has no effect of the installation.

**Comment by vinceliuice** [comment]
What's the error on terminal when you install it you can show me the screenshot

**Comment by iamsubingyawali** [comment]
It doesn't show any errors. The thing is, installation succeeds without any errors but it doesn't apply the theme to the grub.

**Comment by vinceliuice** [comment]
Is kali the only linux on your computer？

**Comment by iamsubingyawali** [comment]
No I have dual boot, Kali along side Windows. I was previously using Manjaro where this theme worked fine. I have recently switched to Kali and it is not working here.

**Comment by iamsubingyawali** [comment]
Any updates on this issue?

**Comment by vinceliuice** [comment]
Fixed now!
