### ISSUE TITLE
[bug] ./install.sh installs default theme instead of displaying list of options

### ISSUE THREAD

**Issue by jedymatt** [vinceliuice/grub2-themes#112]
When `$ sudo ./install.sh` is entered it installs the tela theme.

```
Checking for the existence of themes directory... 
  
 Installing tela color 1080p theme... 
  
 Setting tela as default... 
  
 Updating grub config...
```

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by sisco70** [comment]
Hi,
I fix this issue.
I add the remove theme and "install boot dir" functionality in  #dialogs..
I have improved the handling of dialogs error codes..

Can i make a pull request?

**Comment by sisco70** [comment]
`run_dialog() {
  if [[ -x /usr/bin/dialog ]]; then
    if [[ "$UID" -ne "$ROOT_UID"  ]]; then
      #Check if password is cached (if cache timestamp not expired yet)
      sudo -n true 2> /dev/null && echo

      if [[ $? == 0 ]]; then
        #No need to ask for password
        sudo $0
      else
        #Ask for password
        tui_root_login=$(dialog --backtitle ${Project_Name} \
        --title  "ROOT LOGIN" \
        --insecure \
        --passwordbox  "require root permission" 8 50 \
        --output-fd 1 )
        
        sudo -S echo <<< $tui_root_login 2> /dev/null && echo
        
        if [[ $? == 0 ]]; then
          #Correct password, use with sudo's stdin
          sudo -S "$0" <<< $tui_root_login
        else
          #block for 3 seconds before allowing another attempt
          sleep 3
          clear
          prompt -e "\n [ Error! ] -> Incorrect password!\n"
          exit 1
        fi
      fi
    fi

    # Temporarily re-enable stderr. Required to get the exit codes from the dialog boxes
    set +o  errexit
    # Using pipes to redirect return values ​​allows us to use additional buttons in dialog boxes
    tui=$(dialog --backtitle ${Project_Name} --no-tags \
    --radiolist "Install grub theme into /boot/grub/themes: " 10 52 2 \
    true "Yes" on \
    false "No" off \
    3>&1 1>&2 2>&3 3>&-)
    check_return_value
    boot_opt=$tui

    tui=$(dialog --backtitle ${Project_Name} \
     --no-tags --extra-button --extra-label "Remove" \
    --radiolist "Choose your Grub theme : " 15 40 5 \
      "vimix" "Vimix Theme" off  \
      "tela" "Tela Theme" on \
      "stylish" "Stylish Theme" off  \
      "slaze" "Slaze Theme" off  \
      "whitesur" "WhiteSur Theme" off \
      3>&1 1>&2 2>&3 3>&-)
    check_return_value
    theme=$tui
    
    # If extra button is pressed (return value 3, Cancel is 1, Ok is 0)
    if [[ $retval -eq 3 ]]; then
      remove_opt=true
    else
      tui=$(dialog --backtitle ${Project_Name} \
      --no-tags --radiolist "Choose icon style : " 15 40 5 \
      "white" "white" off \
      "color" "color" on \
      "whitesur" "whitesur" off \
      3>&1 1>&2 2>&3 3>&-)
      check_return_value
      icon=$tui

      tui=$(dialog --backtitle ${Project_Name} --no-tags \
      --radiolist "Choose your Display Resolution : " 15 40 5 \
      "1080p" "1080p (1920x1080)" on  \
      "ultrawide" "1080p ultrawide (2560x1080)" off  \
      "2k" "2k (2560x1440)" off \
      "4k" "4k (3840x2160)" off \
      "ultrawide2k" "1440p ultrawide (3440x1440)" off \
      3>&1 1>&2 2>&3 3>&-)
      check_return_value
      screen=$tui
    fi
    # Disable stderr
    set -o  errexit
  fi
}`

**Comment by vinceliuice** [comment]
@sisco70  No problem!

**Comment by vinceliuice** [comment]
Fixed！
