### ISSUE TITLE
How to take a screenshot ?

### ISSUE THREAD

**Issue by 1457384613gh** [vinceliuice/grub2-themes#120]
What can I do if I would love to take a screenshot when grub2 appear on the  displayer ? 
How can I take a screenshot like yours which you took ?
Or how to preview grub2 and then to take a screenshot.

**Comment by vinceliuice** [comment]
I also want to know! I just use inkscape made that preview pics

**Comment by 1457384613gh** [comment]
> I also want to know! I just use inkscape made that preview pics

Thanks for your reply and how earnest you both are !

**Comment by stuarthayhurst** [comment]
Take a look at [this](https://github.com/hartwork/grub2-theme-preview), you can preview a GRUB theme, and then you can take a screenshot. I'm using it on my [GRUB theme](https://github.com/stuarthayhurst/argon-grub-theme) already to take the preview screenshots.
