### ISSUE TITLE
Grub not detecting Fedora

### ISSUE THREAD

**Issue by calimari0** [vinceliuice/grub2-themes#143]
Just installed the theme and rebooted, and the grub is only detecting Windows (I dual boot Windows 10 and Fedora).

**Comment by vinceliuice** [comment]
Well, this is not a theme issue I think

**Comment by xjvs** [comment]
I also run into this issue, Fedora (f35 beta) doesn't show up in boot menu, only windows shows up.
I'm not 100% sure about that this is caused by the theme, I'm trying to uninstall the theme but got:
```
[grub2-themes]$ sudo ./install.sh -r -t tela

 Checking for the existence of themes directory...
  
 tela grub theme not exist! 
```

**Comment by calimari0** [comment]
> > @xjvs https://ask.fedoraproject.org/t/grub-doesnt-detect-fedora-after-installing-a-grub-theme/17138?u=calimari this thread might help.
> 
> Thank you for your quick reply, however the instructions in that thread don't work for me, at this moment I have to boot up my fedora by manual for every boot. I'm providing my steps for your reference:
> 1. At grub boot menu, press "c" to grub command line prompt.
> 2. type `ls`, you will be able to see all disk partitions.
> ```
> grub> ls
> hd2,gpt1 hd2,gpt2 ...
> ```
> 3. Try to find your boot and root partitions by checking the entries one by one, for example, my root partition is on (hd2,gpt2). so I will be able to see `root` dir under (hd2,gpt2):
> ```
> grub> ls (hd2,gpt6)/
> root/
> ```
> 4. Now you will be able to check the grub config file in your fedora os, check the kernel opts in grub config. For me, it's something like:
> ```
> grub> cat (hd2,gpt6)/root/etc/grub2.cfg
> ...
>   set kernelopts="root=UUID=.... ro rootflags=subvol=root"
> ...
> ```
> 5. Now you are able to boot up the system with `linux` and `initrd` and `boot` commands in grub command line:
> ```
> grub> linux (hd2,gpt6)/root/boot/vmlinuz-5.xxxxx root=UUID=xxx ro rootflags=subvol=root
> grub> initrd (hd2,gpt6)/root/boot/initfs-5.xxxxxxx
> grub> boot
> ```
> Depends on your fedora setup, the instructions could be different. Now you should be able to enter your fedora system, and there will be more possibilities to recover grub entries, though I haven't figure out a solution.

Oh,  so that's how it's done. I couldn't boot into my Fedora system at all, and reinstalled my system. Maybe you could try asking in that thread? I'm by no means an expert at this.

**Comment by vinceliuice** [comment]
Fedora 34 places the grub.cfg file at `/boot/grub2/grub.cfg` now, I'll update the install.sh file
