### ISSUE TITLE
Old Manjaro icon was replaced by new Manjaro icon

### ISSUE THREAD

**Issue by Zesko** [vinceliuice/grub2-themes#148]
The old Manjaro icon shows in this screenshot.
![image](https://user-images.githubusercontent.com/17826352/144714485-c637f2d6-8782-435f-ab4b-740d4d5d6851.png)

But it does not like the currently Manjaro icon:
![image](https://user-images.githubusercontent.com/17826352/144714545-d5a26e11-7b37-478e-8ade-64898f876c63.png)

**Comment by vinceliuice** [comment]
I'll update this

**Comment by Firestar-Reimu** [comment]
But why is the 3 columns not equally wide in the new icon?

![image](https://user-images.githubusercontent.com/65082432/144802169-0171e8c8-b2e2-4678-bf2d-a7c3d7749080.png)
