### ISSUE TITLE
Removing a theme breaks configuration

### ISSUE THREAD

**Issue by The-Plottwist** [vinceliuice/grub2-themes#149]
Hello, recently I wanted to install a new theme and delete the old one by using your script. However, it broke my grub configuration. My understanding is that; by removing, it swaps the current grub configuration with a default one. So I managed to redo my configuration without any issues, nevertheless this can be troublesome for some people.

Cheers.
PS: Thanks for this great theme tool by the way. It is a great pleasure to have.

**Comment by The-Plottwist** [comment]
To suggest a bash friendly solution, I recommend:

- First having a backup with ```cp  PATH_TO_GRUB/grub PATH_TO_GRUB/grub.bak```
- Retrieving the active theme line with ```declare ACTIVE_THEME=$(cat PATH_TO_GRUB/grub | grep "GRUB_THEME" | grep -v "#")```
- Swapping that line with our new theme, which can be ```sed "s|$ACTIVE_THEME|$NEW_THEME|g"```

**Comment by The-Plottwist** [comment]
Hey @vinceliuice, I had had provided a solution, in case you have missed.

**Comment by vinceliuice** [comment]
Could you make a pr for me？

**Comment by The-Plottwist** [comment]
Yes, I would love that, but I am busy at the moment. Is it okay me to do it next week or so?

**Comment by vinceliuice** [comment]
That's ok, thanks!

**Comment by The-Plottwist** [comment]
Hey Vince, don't forget to close fixed issues. (I'm closing this time)
