### ISSUE TITLE
Looks bad on large high res display

### ISSUE THREAD

**Issue by skewty** [vinceliuice/grub2-themes#16]
Grub-theme-vimix

On my 2560x1600px display the boot screen looks more like Atari era.

Would a much higher resolution background file and font size clean it up?

Does GRUB even do font aliasing?

**Comment by zl3one6** [comment]
Hope there would be a method to fix the HiDPI issue, thanks. My screen resolution is 4K, faced with same issue.

**Comment by ArtixZ** [comment]
same here

**Comment by greekbookhero** [comment]
> same here

maybe cause image resolution is small?

**Comment by vinceliuice** [comment]
Now 2k and 4k display supported!
