### ISSUE TITLE
Stuck on system recovery after installing vimix

### ISSUE THREAD

**Issue by GRR3ED** [vinceliuice/grub2-themes#182]
So I installed vimix grub2 theme and now I'm stuck on startup menu! I can't boot into my grub!!

This is what it shows

![PXL_20221101_092950009](https://user-images.githubusercontent.com/58597122/199157308-24350b49-2416-4e76-b56f-9e265efb1155.jpg)

What can I do to fix this?

**Comment by vinceliuice** [comment]
What's your system version?

**Comment by vinceliuice** [comment]
How did you installed it?

**Comment by GRR3ED** [comment]
@vinceliuice Arch Linux 6.0.2

And I installed it via install script

**Comment by vinceliuice** [comment]
Arch linux updated grub2 https://archlinux.org/news/grub-bootloader-upgrade-and-configuration-incompatibilities/

**Comment by vinceliuice** [comment]
Try click F9 to open boot menu and choose the right device to start

**Comment by GRR3ED** [comment]
I booted using first option
![PXL_20221101_115330551](https://user-images.githubusercontent.com/58597122/199169937-e40d0856-b5d0-4708-b683-16f1f672019b.jpg)

but it takes me to back to the same startup menu

**Comment by GRR3ED** [comment]
I'm thinking of booting with liveCD and regenerating GRUB menu

**Comment by vinceliuice** [comment]
Maybe the problem is the boot efi file, if that so, you gona need reinstall grub efi file into efi boot partition

**Comment by vinceliuice** [comment]
As Arch wiki said:
After a grub package update it is advised to run both, installation and regeneration of configuration:

grub-install (efi partition)

grub-mkconfig -o /boot/grub/grub.cfg

**Comment by GRR3ED** [comment]
Didn't read through the manual LOL 

Thought the script did it for you.....

**Comment by GRR3ED** [comment]
Fixed it via live-USB
