### ISSUE TITLE
terminal user interface (tui) redundant  

### ISSUE THREAD

**Issue by Jukoo** [vinceliuice/grub2-themes#19]
the installation by tui is redundant

**Comment by vinceliuice** [comment]
You can still use sudo ./install.sh -"options" to install the theme you want directly, so it will not use gui but install it directly from the command line. I provide the gui for the novice user, because the script can not run without options behind ./install.sh.

**Comment by Jukoo** [comment]
I fixed the issue

**Comment by vinceliuice** [comment]
Works great, Thanks!
