### ISSUE TITLE
[REQUEST] ChromeOS Icon

### ISSUE THREAD

**Issue by yuriuseu** [vinceliuice/grub2-themes#191]
I'm using the whitesur theme with [brunch](https://github.com/sebanc/brunch) and it looks good. Just wondering what it looks like with a ChromeOS icon. Would love to see a plain white and colored icon if possible.

Here's the preview (camera quality is bad, but it looks good in actual):

![IMG_20230116_191131](https://user-images.githubusercontent.com/98409600/212666330-4acde3b5-6e43-45a3-938f-83b10c62cd59.jpg)

The background image used is this:

![chromeos](https://preview.redd.it/fpgwj9uolvq41.png?width=640&crop=smart&auto=webp&v=enabled&s=aae9c27d3a37fd629efe19cbcd7ee3e58ab3d5bf)

**Comment by vinceliuice** [comment]
I need your `grub.cfg` file

**Comment by yuriuseu** [comment]
@vinceliuice Default grub boot files are available in the brunch [repository](https://github.com/sebanc/brunch/tree/r107/efi-partition/efi/boot) itself (I'm currently using the latest stable [`r107`](https://github.com/sebanc/brunch/tree/r107) branch).

All I did is mount the EFI partition of my current setup and install `whitesur` under [`themes`](https://github.com/sebanc/brunch/tree/r107/efi-partition/efi/boot/themes) directory and set the default theme from [`theme.cfg`](https://github.com/sebanc/brunch/blob/r107/efi-partition/efi/boot/theme.cfg):

```
grub_theme=whitesur

#loadfont /efi/boot/themes/$grub_theme/UbuntuMonoBold28.pf2
set theme=/efi/boot/themes/$grub_theme/theme.txt
export theme

set gfxmode=auto,1024x768
set gfxpayload=text
terminal_output gfxterm
```

Here's a reference of the actual `grub.cfg` you're looking for:

```
set timeout=2
regexp --set disk "(^.+)(,gpt)" $root
source /efi/boot/theme.cfg
source /efi/boot/settings.cfg

menuentry "ChromeOS" --class "brunch" {
	if [ -z $verbose ] -o [ $verbose -eq 0 ]; then
		linux ($disk,7)$kernel boot=local noresume noswap loglevel=7 cros_secure cros_debug options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params \
	  		console= vt.global_cursor_default=0 brunch_bootsplash=$brunch_bootsplash quiet
	else
		linux ($disk,7)$kernel boot=local noresume noswap loglevel=7 cros_secure cros_debug options=$options chromeos_bootsplash=$chromeos_bootsplash $cmdline_params
	fi
	initrd ($disk,7)/lib/firmware/amd-ucode.img ($disk,7)/lib/firmware/intel-ucode.img ($disk,7)/initramfs.img
}

menuentry "ChromeOS (settings)" --class "brunch-settings" {
	linux ($disk,7)/kernel boot=local noresume noswap loglevel=7 cros_secure cros_debug options= chromeos_bootsplash= edit_brunch_config=1
	initrd ($disk,7)/lib/firmware/amd-ucode.img ($disk,7)/lib/firmware/intel-ucode.img ($disk,7)/initramfs.img
}
```

**Comment by yuriuseu** [comment]
Class name is just `brunch` (which boots the actual OS) and `brunch-settings` (which launches the [Brunch Configuration Menu](https://github.com/sebanc/brunch/blob/main/troubleshooting-and-faqs.md#brunch-configuration-menu) to set the default kernel, kernel parameters, boot splash themes, etc.. and reboots the device).

It is safe to use `brunch` (and/or `chromeos` as a substitute) class name I guess, since `brunch` is just the loader to ChromeOS (ChromeOS itself obfuscates its own boot loader configuration stuff).

**Comment by vinceliuice** [comment]
Ok, I'll add those icons
