### ISSUE TITLE
Icon for folders

### ISSUE THREAD

**Issue by NLDev** [vinceliuice/grub2-themes#2]
Is there a way to add an Icon for folders like "_`Advanced Options for Ubuntu`_" or similar?
Basically for the category "submenu" in `grub-customizer`

**Comment by KolinGuo** [comment]
I was searching on the web and found across this [post](https://askubuntu.com/questions/511237/grub2-icons-question) relating to your issue. 

Basically, `update-grub` uses the setup scripts inside folder `/etc/grub.d` to generate grub boot entries and grub themes use the `class` of each boot entry to associate an icon with it. 
Therefore, you need to modify the setup scripts by adding a `class` to each boot entry whose icon you want to change. 

For the "`Advanced Options for Ubuntu`" submenu you mentioned, you need to modify the script `/etc/grub.d/10_linux` (or other similar file names depending on your Linux distribution). 

- Locate the line `echo "submenu '$(gettext_printf "Advanced options for %s" "${OS}" | grub_quote)' \$menuentry_id_option 'gnulinux-advanced-$boot_device_id' {"`
- Modify it by adding `${CLASS}` 
This will set this submenu to the same class of your Linux distribution, i.e. Ubuntu, Arch, etc.
If you want a different icon, you should add `--class [ICON_NAME]` with an existing ICON_NAME in `assets` of this repo.
- It should now looks like `... grub_quote)' ${CLASS} \$menuentry_id_option ...`
or `... grub_quote)' --class [ICON_NAME] \$menuentry_id_option ...`

In my situation, I also want to change the "`System Setup`" boot entry icon. Below are steps to do so.

- Use `grub customizer` to find the setup script that generates the boot entry. In my case, it's `/etc/grub.d/30_uefi-firmware`
- Add a line `CLASS="--class [ICON_NAME]"` below the two `export` lines
- Add the CLASS option in the menuentry line
`menuentry '$LABEL' ${CLASS} \$menuentry_id_option 'uefi-firmware'`

After you finished modifying the classes, run the `install.sh` script of this repo to update the changes.

**Comment by NLDev** [comment]
Awesome! Thank you for the heads up :)
Ill try that out and will close this issue now, as it's not directly related to the theme. 
Thank's for letting me know!
