### ISSUE TITLE
My windows just disappear!

### ISSUE THREAD

**Issue by chinabestcountry** [vinceliuice/grub2-themes#213]
I'm happy that i find a wonderful grub theme on github and it was really beautiful! :D
But unfortunely,when i install it on my arch linux ,it works but my windows boot just disappear,but i can use my windows through the grub terminal.
The grub works well before i install the theme and im using Bios + MBR
can some1 help me? plzzz
have a good day!

**Comment by HarshNarayanJha** [comment]
Try reinstalling grub. Check if os-prober detects Windows installation or not.

**Comment by chinabestcountry** [comment]
Thanks!
The problem solve after i reinstall my grub config
