### ISSUE TITLE
There's no way to select a different theme on the dialog interface

### ISSUE THREAD

**Issue by raulgrangeiro** [vinceliuice/grub2-themes#225]
Good afternoon,

I've downloaded the theme pack and when I executed sudo ./install.sh and the dialog appeared I tried to change from different theme from default but it didn't work, there's no button that alows you to change from default option, it just install the Tela theme and even it apears the options, they can't be selected.

How can I do different? Is it  a bug?

**Comment by vinceliuice** [comment]
use up and down Keyboard keys to change line, and space key to Confirm your selection

**Comment by vinceliuice** [comment]
You are welcome !
