### ISSUE TITLE
Installer fails due to whitespaces

### ISSUE THREAD

**Issue by Dvlnst** [vinceliuice/grub2-themes#24]
Hi,

First of all, thank you for these awesome themes. When you run install.sh script inside a directory with whitespaces, it fails because variables with paths should be used inside "". 

As a workaround, I edited all ${REO_DIR} to "${REO_DIR}" and It works.

Kind regards.

**Comment by jamezrin** [comment]
Open a MR and you can say you have contributed!

**Comment by vinceliuice** [comment]
Fixed now!
