### ISSUE TITLE
Add FreeBSD LOGO ?

### ISSUE THREAD

**Issue by javashin** [vinceliuice/grub2-themes#25]
PLEASE.

**Comment by javashin** [comment]
???

**Comment by KolinGuo** [comment]
You may want to read my comments here #2 
You could include a custom icon in `assets` folder and named it the `class` name of your boot entry (Linux distribution).

**Comment by ElianVanCutsem** [comment]
Hey, I added the free BSD logo in the theme (color only).
I know this issue was open longtime ago. If you're willing to test this, that would be wonderful! @javashin

**Comment by ElianVanCutsem** [comment]
@javashin this issue should be closed.
