### ISSUE TITLE
Setting icons

### ISSUE THREAD

**Issue by ApertureDevelopment** [vinceliuice/grub2-themes#26]
Hello,

I would like to know how does someone set the icons? 

In my grub just one symbol loads and its the one of Windows, nothing else I add has a icon, not Shutdown, not Reboot, not Fedora etc. So how does someone set the icons?

**Comment by mateosss** [comment]
In `/boot/grub/grub.cfg` look for the entries without icons, and see if they have a `--class <something>` flag. If so, just add `<something>.png` to `/boot/grub/themes/<your-theme>/icons/` and you will be good to go.

**Comment by jgabriel98** [comment]
what would be the class for subfolder (submenu) entry? like the "Advanced options for ubuntu"

**Comment by jgabriel98** [comment]
which command i must run to these changes take effect?
i ran `sudo update-grub`, but it seems that i did not took any effect

**Comment by mateosss** [comment]
Did you manually add `--class` in `grub.cfg`? If so, when doing `update-grub` they will be removed. For the changes to stay you must either not run `grub-update` (which is certainly a bad long term idea since it will be run every time there is a system upgrade) or tinker around with the same scripts a program like `grub-customizer` modifies. I don't remember very well which ones those are right now :upside_down_face:.

**Comment by jgabriel98** [comment]
### solution:
read the file _/boot/grub/grub.cfg_ and look for the `### BEGIN  <config_file>###`  _code_  `### END  <config_file>###`  sections, for example:
```
### BEGIN /etc/grub.d/10_linux ###
function gfxmode {
	set gfxpayload="${1}"
	if [ "${1}" = "keep" ]; then
		set vt_handoff=vt.handoff=7
	else
		set vt_handoff=
	fi
}
set linux_gfx_mode=keep
export linux_gfx_mode
menuentry 'Ubuntu' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-da66e1bb-a1d2-4499-a8fd-f5b8522178a5' {

    more code here
    .
    .
    .

### END /etc/grub.d/10_linux ###
```
this is telling us that everything between that is configured by the _/etc/grub.d/10_linux_ file.
so now you know which files determines each grub sections (for the example, _/etc/grub.d/10_linux_ configures the Ubuntu entry).


Now you just have to edit the corresponding file, to make it have `--class class_name` on the `menuentry` line, where `class_name` would be the same name of the icon file you want to show up (without the extension of course)

example of what i did:
 i've changed the file in /etc/grub.d/10_linux, making these changes:

changed
```
CLASS="--class gnu-linux --class gnu --class os"
```
to
```
CLASS="--class gnu-linux --class gnu --class os"
CUSTOM_CLASS="${CLASS}"
```

and changed:
```
echo "submenu '$(gettext_printf "Advanced options for %s" "${OS}" | grub_quote)' \$menuentry_id_option 'gnulinux-advanced-$boot_device_id' {"
```
to (just added `${CUSTOM_CLASS}`)
```
echo "submenu '$(gettext_printf "Advanced options for %s" "${OS}" | grub_quote)' ${CUSTOM_CLASS} \$menuentry_id_option 'gnulinux-advanced-$boot_device_id' {"
```

#### Final Steps

Now you just run `sudo update-grub`

**Comment by Dragon8oy** [comment]
I feel like this should be summarised and added to a wiki or the README, I'll try work on it later

**Comment by Dragon8oy** [comment]
After looking into this, I can't figure it out on my Debian machine. If someone could summarise this as a set of instructions for markdown, that'd be amazing, thanks.
