### ISSUE TITLE
Auto comment GRUB_TERMINAL_OUTPUT="console"

### ISSUE THREAD

**Issue by PsiACE** [vinceliuice/grub2-themes#30]
Thank you for your work, but consider auto-commenting `GRUB_TERMINAL_OUTPUT="console"`.
Or add a small tip in the `README.md`.

**Comment by mridul303** [comment]
Even I agree with this. I spent over 3 hours figuring out why the themes were not working. It finally worked after commenting out the GRUB_TERMINAL_OUTPUT="console" line in /etc/default/grub file

**Comment by Dragon8oy** [comment]
If @vinceliuice agrees this is a good idea, I'd be happy to make a pull request :)

**Comment by vinceliuice** [comment]
NO problem! @Dragon8oy

**Comment by Dragon8oy** [comment]
#94 will close this

**Comment by breversa** [comment]
I'm late to the party but why not also auto-comment `GRUB_TERMINAL_OUTPUT="hidden"` too ?

**Comment by Dragon8oy** [comment]
Oops, seems I missed the point of this issue and fixed another bug instead...

**Comment by Dragon8oy** [comment]
Wait, what does `GRUB_TERMINAL_OUTPUT="hidden"` do? and what's the difference between that and `GRUB_TERMINAL_OUTPUT="console"`?

**Comment by breversa** [comment]
My bad, I confused with "GRUB_TIMEOUT_STYLE=menu" !

Le dim. 18 oct. 2020 à 12:48, Stuart Hayhurst <notifications@github.com> a
écrit :

**Comment by Dragon8oy** [comment]
I've written auto-commenting for `GRUB_TERMINAL_OUTPUT=console` and `GRUB_TERMINAL=console`, what does `GRUB_TIMEOUT_STYLE=menu` do, and is it necessary?

**Comment by breversa** [comment]
From what I understand, it forces GRUB to display the menu instead of hiding it : https://www.fosslicious.com/2020/01/show-and-hide-grub-menu-ubuntu-linux.html

(Could someone confirm ? I've alway found GRUB's options to be uselessly difficult to comprehend, with lots of double-negative)

**Comment by Dragon8oy** [comment]
From what I understand, it prevents grub automatically displaying when booting, if it's set to hidden. I don't think this should be commented, as users many not want grub to appear automatically.

The theme will still apply to grub, regardless of the value of the setting, and grub can still be displayed by pressing whatever key triggers it while booting.
