### ISSUE TITLE
Not able to change the Background

### ISSUE THREAD

**Issue by Henil** [vinceliuice/grub2-themes#31]
After installing Slaze grub theme I was trying to change the background of it by replacing the 
> "background.jpg"

 file in /boot/grub/themes/Slaze/background.jpg with the desired jpg file and then renaming it to background.jpg. And then updating the grub using 

> "sudo update-grub"

But it started giving a weird error during boot up called "hwmatch not found" and the default grub been launced. I thought it might have dimension issues so I tried using the default slaze background and overlapping my image in gimp. And it still gives the same error.

**Comment by vinceliuice** [comment]
That's because your grub installation is incomplete, the hwmatch module is missing. you can run sudo dpkg-reconfigure grub-pc or reinstall grub

**Comment by HenilDedania** [comment]
No, I have tested it as soon as I replace my background image with the original slaze background it works fine. Thats the reason I have opened a issue in here. There is something else that is creating the problem.

**Comment by HenilDedania** [comment]
So I have tried changing the actual Picture and it worked!

> [The Picture I was trying to use](https://imgur.com/a/KwgUqVp)
> [The Picture that worked](https://imgur.com/a/r7NJRuH)

I think this is something related to dimensions as the image I was trying to use is less than 1920 x 1080. But I am not able to understand how it triggers hwmatch error. And also why does grub does not automatically stretch the image as done when I use it in my desktop background. As I have tried imposing my image on the default slaze background image using gimp and that didnt work as well.

**Comment by vinceliuice** [comment]
Maybe grub not support all jpg images,

**Comment by Henil** [comment]
As far as I think the command "hwmatch" has something to do with stretching or compressing images, which is incomplete or has some bug that gets triggered when a smaller image is provided which causes that bug. I tried researching for the hwmatch but could not find any documentation for it. Just a guess I am not into kernel or so.
