### ISSUE TITLE
Tiny font in HiDPI display

### ISSUE THREAD

**Issue by abougouffa** [vinceliuice/grub2-themes#33]
I have a HiDPI (retina) display, the font size of the theme is tiny!

**Comment by vinceliuice** [comment]
I'll fix this

**Comment by vinceliuice** [comment]
I add bigger size fonts and icons for the 2k and 4k version, but I don't have HiDPI display, so could you help me test the new one, you can take a picture to me or just tell me if it's works well on your disply?

**Comment by abougouffa** [comment]
Hi @vinceliuice , Thank you for your responsiveness
I tested your new script, but I still get a tiny font

![IMG_20191024_093441](https://user-images.githubusercontent.com/3716399/67464397-908e5700-f643-11e9-8dae-4d058390d1fe.jpg)

Here the size wrt a stylus!
![IMG_20191024_093517](https://user-images.githubusercontent.com/3716399/67464408-95eba180-f643-11e9-962c-288f4ff6436b.jpg)

**Comment by vinceliuice** [comment]
Did you installed the 4k version? you can run sudo ./install -t -4 to install this, maybe you just installed the default version, because default one is for 1080p display

**Comment by vinceliuice** [comment]
![2019-10-24 16-33-09 的屏幕截图](https://user-images.githubusercontent.com/7604295/67467798-03b3bf80-f67c-11e9-956c-7c025f00494a.png)

**Comment by abougouffa** [comment]
Yep, I used `./install.sh -4 -t`

**Comment by vinceliuice** [comment]
So it's still the same on your display without any change? This is weird because the fonts and icons are doubled on my screen. by the way I changed the theme path to /usr/share/grub/themes,  could you help me check this file /etc/default/grub, does it edit the right path of grub theme?

**Comment by abougouffa** [comment]
Yes, the `GRUB_THEME` in `/etc/default/grub` points to the right path `"/usr/share/grub/themes/Tela/theme.txt"`

I noticed that even if I launches `install.sh` with `-4` or `-2` arguments, it prints always `Installing Tela 1080p theme...`
![Screenshot from 2019-10-24 14-09-16](https://user-images.githubusercontent.com/3716399/67484487-7adf5880-f668-11e9-9a7b-d0fef4bdfbe8.png)

Now when I launched `install.sh` directly and used the **dialog** graphical interface, it works perfectly and prints `Installing Tela 4k theme...`
![Screenshot from 2019-10-24 14-10-00](https://user-images.githubusercontent.com/3716399/67484680-e32e3a00-f668-11e9-9974-09c66f5417ed.png)

Now the font and the icons have the right size
![IMG_20191024_141515](https://user-images.githubusercontent.com/3716399/67484756-08bb4380-f669-11e9-9de2-7c3fe6600a07.jpg)

So the problem was in the command line arguments, I guess they aren't handled correctly!

Thank you for your responsiveness @vinceliuice

**Comment by vinceliuice** [comment]
Ok, now I got the problem, I'll fix this!
