### ISSUE TITLE
Font anti-aliasing looks very bad

### ISSUE THREAD

**Issue by pkkid** [vinceliuice/grub2-themes#34]
I tried a bunch of resolutions and the anti-aliasing on the font looks really bad. Nothing like the screenshots posted. I'm running this on a 21:9 monitor, maybe that is why? My screen resolution is 3440x1440 which is not an option when installing the themes.

Here is an example, forgive my horrible photo.
https://imgur.com/a/9Dif0nl

**Comment by vinceliuice** [comment]
You can run sudo ./install.sh -t -4 to install the 4k version

**Comment by vinceliuice** [comment]
Download the last update of this theme

**Comment by vinceliuice** [comment]
The font I have changed it back
