### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by lb-d** [vinceliuice/grub2-themes#35]
I installed the last version **sudo ./install.sh -v** but can uninstall with the command  **sudo ./install.sh -r -v**   to install the latest version . I just get     Vimix grub theme not exist! 

Can I just delete it from /boot/grub/themes  ?  Or reinstall grub? Not sure what to do here.

**Comment by vinceliuice** [comment]
Yes you can, I changed the theme dir to /usr/share/grub/themes, so you run -r it'll just remove the themes on new dir, but the old one on  /boot/grub/themes, you can just delete the Vimix folder

**Comment by lb-d** [comment]
Nice.  And looking through your install scripts on Tela, Matcha and others I guess this will rm the dir before installing, so we can just run `git pull`  then install to get the newer versions? 

`  [[ -d "${THEME_DIR}/${name}" ]] && rm -rf "${THEME_DIR}/${name}"
    mkdir -p "${THEME_DIR}/${name}"`

And thanks for all your great work, it make linux a pleasure to use.

**Comment by vinceliuice** [comment]
Yes, you can reinstall to get the newer version
