### ISSUE TITLE
Installation of dialog package fails on Fedora

### ISSUE THREAD

**Issue by IzNoGud78** [vinceliuice/grub2-themes#36]
Before executing the installation of any package dnf asks the user for confirmation, the default choice is not to install the package so, not receiving confirmation, dnf doesn't install the dialog package.

To avoid this error, you can add the -y (or --assumeyes) option to automatically answer yes to all questions, therefore, the correct command on line 191 of the install.sh file should be:

`sudo dnf install -y dialog`

or

`sudo dnf install --assumeyes dialog`

**Comment by vinceliuice** [comment]
Thanks！I'll add this to fix it
