### ISSUE TITLE
The option 2560x1440 does not fit well with my monitor.

### ISSUE THREAD

**Issue by gusbemacbe** [vinceliuice/grub2-themes#38]
Hello!

My monitor is ultra-wide and is 2560x1080. In the grub, the text got very bigger.

**Comment by vinceliuice** [comment]
So you just installed 2k version and got this？why not try 1080p
Version

**Comment by vinceliuice** [comment]
Could you take a picture to me？

**Comment by gusbemacbe** [comment]
> So you just installed 2k version and got this？why not try 1080p

If I set 1080p, the ultrawide monitor will have two black sides.

> Could you take a picture to me？

![photo_2019-11-07_22-54-43](https://user-images.githubusercontent.com/2257024/68443113-da358080-01b1-11ea-9ae6-770279511797.jpg)

**Comment by vinceliuice** [comment]
Then you manually set the resolution of grub，edit /etc/default/grub  find GRUB_GFXMODE= and edit GRUB_GFXMODE=2560x1080×32

**Comment by vinceliuice** [comment]
then update your grub

**Comment by gusbemacbe** [comment]
I set 1080p and added `GRUB_GFXMODE`, but the text is still bigger:

![image](https://user-images.githubusercontent.com/2257024/68444024-6a74c500-01b4-11ea-9cd7-f24b869a78c1.png)

**Comment by gusbemacbe** [comment]
@vinceliuice 

It is solved. In reference to https://www.reddit.com/r/linuxquestions/comments/dtd6jt/the_text_is_too_big_in_the_grub_in_my_ultrawide/.

**Comment by vinceliuice** [comment]
Great！I'll add this solution into README！
