### ISSUE TITLE
Install script forgot to create subfolder "Vimix"

### ISSUE THREAD

**Issue by svergeylen** [vinceliuice/grub2-themes#4]
It seems the files are copied into /boot/grub/themes/ directly, without a subfolder "Vimix".

But the configuration ine in /boot/default/grub/ points to a subfolder /boot/grub/themes/Vimix/

The install script should put the files in a subfolder directly, and also manage the correct owner of the files (root) and not the current user.

**Comment by jackreez** [comment]
The problem you've mentioned above will occur
if you don't already have the folder "themes" inside " /boot/grub/"
If the "themes" folder exists it works fine.

**Comment by vinceliuice** [comment]
Fixed now
