### ISSUE TITLE
Font doesn’t apply with theme

### ISSUE THREAD

**Issue by Eg015** [vinceliuice/grub2-themes#43]
The font shown in the previews doesn’t apply with the theme. I used the install.sh script that came with it, and the font didn’t change.
![357C871A-FAF2-4AEC-A9BC-7FA772BF7C97](https://user-images.githubusercontent.com/58460873/70028870-a45f9e00-159d-11ea-9994-8c896871185a.jpeg)

**Comment by PieterAndriesBerg** [comment]
My font is also a bit pixelated

**Comment by vinceliuice** [comment]
Grub cannot use the advanced functions of the graphics card, and cannot achieve the effect of font blurring

**Comment by PieterAndriesBerg** [comment]
It doesn't look like as sharp on the screenshot

**Comment by vinceliuice** [comment]
The pictures are not screenshots I use inkscape made them

**Comment by Eg015** [comment]
So I can’t apply the font?

**Comment by vinceliuice** [comment]
All font will look sharp on grub, because grub don't support any blurring effect.

**Comment by ileri** [comment]
> Grub cannot use the advanced functions of the graphics card, and cannot achieve the effect of font blurring

OK, grub cannot make a blurred font, but I think that, to improve the visual pleasure, we can change these texts with images that generated in installation stage. So, grub will not show texts as "text", instead will show as "images". In this case, we can use the font whatever we desire and apply any effect to them. 

This may not be a good suggestion, but the people that install this themes to their grub, want to improve the appearance.

**Just a suggestion.**

**Comment by NgoHuy** [comment]
You need to check `file /boot/grub/fonts/*.pf`. If it mismatchs font size and your theme, it's pixelated. By default, theme set Unicode fonts but if /boot/grub/fonts/unicode.pf exists, it will use it. Change it to your fonts manually.
