### ISSUE TITLE
Theme not detected by grub2

### ISSUE THREAD

**Issue by xcfrg** [vinceliuice/grub2-themes#44]
I'm using ubuntu 18.04.03, dual booted with windows 10. (UEFI). When installing themes from this repo, they aren't detected by grub2 at all. Other themes (not by you) do work. I'm assuming this is a efi thing as the instructions you have in your readme for finding your resolution supported by grub said vbeinfo and didn't say anything about it being videoinfo

**Comment by mridul303** [comment]
Did you try commenting out GRUB_TERMINAL_OUTPUT="console" line in /etc/default/grub file? I had the same issue and commenting out that line made grub2 detect the theme.

**Comment by Dragon8oy** [comment]
This should've been fixed by a recent pull request. Can this be closed?
