### ISSUE TITLE
Not work on fedora 31 

### ISSUE THREAD

**Issue by mabed-fr** [vinceliuice/grub2-themes#46]
[output.txt](https://github.com/vinceliuice/grub2-themes/files/3979971/output.txt)
Hello,

The script do not work on fedora 31 ?

**Comment by VergeDX** [comment]
Hi, I'm using Fedora 32. I found the solution:  
in `/etc/default/grub` file, there is a default settings `GRUB_TERMINAL_OUTPUT="console"`  
backup the `grub` file, modify the file, comment that line.  
See also [https://unix.stackexchange.com/questions/264639/fedora-uefi-grub-theme-not-being-properly-set](https://unix.stackexchange.com/questions/264639/fedora-uefi-grub-theme-not-being-properly-set)  
@BedoM

**Comment by bryce-carson** [comment]
> in `/etc/default/grub` file, there is a default settings `GRUB_TERMINAL_OUTPUT="console"`
> @BedoM

I'm using Fedora 32 as well, and that did not work for me.

**Comment by Dragon8oy** [comment]
If this is an issue, it looks like the grub config isn't being updated. This might've been fixed by a commit since then, so can you try again please? Thanks :)

**Comment by Prn-Ice** [comment]
Fixed it by running 
```sh
sudo grub2-mkconfig -o /boot/grub2/grub.cfg
```
