### ISSUE TITLE
Install Miss

### ISSUE THREAD

**Issue by gvoze32** [vinceliuice/grub2-themes#47]
I try to choose all theme, but theme keep installing Tela.

**Comment by ElianVanCutsem** [comment]
have you used the GUI installer? If so, you probably forget to press the spacebar to select an item before pressing enter to advance. Tela gets installed because it's the default option.

**Comment by Dragon8oy** [comment]
Considering there hasn't been any update to this for over half a year, and @gvoze32 hasn't replied, can this be closed?

**Comment by gvoze32** [comment]
Sorry, thanks for the answer @ElianVanCutsem 

I can install it perfectly

**Comment by ElianVanCutsem** [comment]
No prob man ☺️
