### ISSUE TITLE
Missing Slaze image in 2k and 4k

### ISSUE THREAD

**Issue by bmihaila** [vinceliuice/grub2-themes#49]
It seems that the `background-slaze.jpg` file was not uploaded in 2k and 4k resolution with commit https://github.com/vinceliuice/grub2-themes/commit/fa55fb3a81afffba10f501801b2a9bd31cfd805c thus that theme can't be used in higher resolutions atm.

**Comment by mental32** [comment]
+1 Just ran into this issue too

**Comment by vinceliuice** [comment]
Because this version was uploaded by one user, so I don't have the slaze source file, I can't make 2k and 4k resolution pictures of slaze.

**Comment by bmihaila** [comment]
@vinceliuice then can you ask that user to provide the file? 
If not you need to at least fix the install script for Slaze 4k as it just finishes without errors and on reboot Grub errors out as the proper file was not copied to `background.jpg`. So the script should not allow installing the 4k Slaze theme in the first place and maybe you should mention that in the readme, too.

**Comment by vinceliuice** [comment]
No problem! I'll fix this

**Comment by Dragon8oy** [comment]
Unless I'm mistaken, this is fixed isn't it? If not I can try work on it, otherwise this should probably be closed. :)
