### ISSUE TITLE
安装脚本有个地方写错了

### ISSUE THREAD

**Issue by jiqing112** [vinceliuice/grub2-themes#5]
sh脚本的第14行，路径是 /boot/**grub2**/themes

` cp -a Vimix /boot/grub/themes`
路径应该是
` /boot/grub2/themes`
所以在改/etc/default/grub文件的路径也应该为 grub2，不然找不到也应用不上的，我是这个问题，改过来之后主题就用上了。
感谢作者制作的这么好看的主题

**Comment by vinceliuice** [comment]
好久没有整理这个主题了,现在修复了
