### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by Findoss** [vinceliuice/grub2-themes#54]
symbol `×`

https://github.com/vinceliuice/grub2-themes/blob/4c063209496bf39f36e44e2b0d27229f16ad7132/install.sh#L128

**Comment by vinceliuice** [comment]
Did you get any issue about this?

**Comment by Findoss** [comment]
I did not install the theme, but the correct syntax 

> `auto`,`WIDTHxHEIGHT`, or `WIDTHxHEIGHTxDEPTH`.

[https://www.gnu.org/software/grub/manual/grub/grub.txt](url)

**Comment by vinceliuice** [comment]
2k resolution is 2560×1440, is there anything wrong?

**Comment by Findoss** [comment]
> 2k resolution is 2560×1440
 
 it's true

pay attention `2560×1440` and `2560x1440`
![image](https://user-images.githubusercontent.com/5212244/74822870-d9ff6200-5316-11ea-8aeb-f17ca32d3d21.png)
I understand this is a different symbol, does it matter?

**Comment by vinceliuice** [comment]
Oh, didn't notice that, I'll fix this!

**Comment by vinceliuice** [comment]
Thanks!
