### ISSUE TITLE
Theme dir for encrypted drive

### ISSUE THREAD

**Issue by mlojewski-me** [vinceliuice/grub2-themes#58]
If my drive is encrypted directory `/usr/share/grub/themes` is not available at boot menu, it works only when It put theme in unencrypted partition `/boot`.
Maybe there should be flag which change `THEME_DIR` path to `THEME_DIR=/boot/grub/themes` for example `-b --boot` ?

**Comment by cmlnet** [comment]
I would really appreciate that, too.

**Comment by vinceliuice** [comment]
No problem! I'll add this option

**Comment by vinceliuice** [comment]
Now it's ok
