### ISSUE TITLE
Installation script doesn't provide a different paths

### ISSUE THREAD

**Issue by IzNoGud78** [vinceliuice/grub2-themes#6]
`cp -a StylishDark /boot/grub/themes`

On fedora (the version I used is currently 28) the path doesn't exist, I had to change the path with the correct one that is /boot/**grub2**/themes.
It would probably be better to use an alternative path like /usr/share/grub/themes

`echo "GRUB_THEME=\"/boot/grub/themes/StylishDark/theme.txt\"" >> /etc/default/grub`

In this case, if the copy of the files was not successful with the previous command (as it happened in my case, not finding the path), specifying an incorrect path will not find any theme when the grub will be updated.

`elif has_command grub2-mkconfig; then`
`grub2-mkconfig -o /boot/grub/grub.cfg`

In this case, it isn't considered an alternative path for uefi systems which, in my case, is /boot/efi/EFI/fedora/grub.cfg

To solve the problem, I had to change the various paths manually before running the script.
[Install.txt](https://github.com/vinceliuice/grub2-themes/files/2407453/Install.txt)

**Comment by NOVAglow** [comment]
I'm a Fedora user as well and I can confirm this.

**Comment by vinceliuice** [comment]
Sorry for this, did not notice that before, Now I add this fix to my theme
