### ISSUE TITLE
Icon arrangement

### ISSUE THREAD

**Issue by Just-null** [vinceliuice/grub2-themes#60]
Hi, I ’m from China, and I like your theme very much. I feel that the icons are arranged in a horizontal way. I do n’t know if it can be set? Or do you have time to design a theme with icons arranged horizontally?

**Comment by vinceliuice** [comment]
我也中国的，这个做不到的，因为grub2不支持，除非是burg

**Comment by Just-null** [comment]
这样啊，谢谢------------------ 原始邮件 ------------------
发件人: "Vince"<notifications@github.com>
发送时间: 2020年4月8日(星期三) 下午2:01
收件人: "vinceliuice/grub2-themes"<grub2-themes@noreply.github.com>;
抄送: "Just-null"<3040705657@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vinceliuice/grub2-themes] Icon arrangement (#60)




 
我也中国的，这个做不到的，因为grub2不支持，除非是burg
 
&mdash;

**Comment by vinceliuice** [comment]
不客气
