### ISSUE TITLE
how to compile/generate the readme.md theme screeshots

### ISSUE THREAD

**Issue by jgabriel98** [vinceliuice/grub2-themes#64]
Hi, i didn't know how else to reach this git maitaner,

so i wil be quick and erase this issue(if requested).

How did you generated the themes screenshot images under _screenshots_ folder?

and related to this, is there any way to"compile" the project so is shows how it would look a theme with the selected settings?

**Comment by Dragon8oy** [comment]
I'm also curious how this was done :)

**Comment by vinceliuice** [comment]
I just use inkscape make them, it's not real `screenshot` just a picture

**Comment by Dragon8oy** [comment]
Oh okay, that makes sense

**Comment by Dragon8oy** [comment]
Can this be closed? Thanks :)
