### ISSUE TITLE
Ubuntu 20.04 can't find hwmatch

### ISSUE THREAD

**Issue by nullmax** [vinceliuice/grub2-themes#66]
After installing the grub theme, next boot grub show errors below:
```
error: can't find hwmatch
error: invalid arguments
press any key to continue:
```
Then jump to the default grub screen.

**Setting  GRUB_GFX_MODE didn't work.**

Here is the system info:
OS: Ubuntu 20.04 LTS x86_64 
Kernel: 5.4.0-31-generic 
Resolution: 1920x1080 
DE: GNOME 
CPU: Intel i7-8750H (12) @ 4.100GHz 
GPU: Intel UHD Graphics 630

**Comment by vinceliuice** [comment]
because your grub installation is incomplete, the hwmatch module is missing

**Comment by nullmax** [comment]
> because your grub installation is incomplete, the hwmatch module is missing

I installed Ubuntu Minimal by default settings.  I googled this problem, and not found a solution. Can you give me some suggestions?

**Comment by vinceliuice** [comment]
You should run `sudo dpkg-reconfigure grub-pc` and instruct it to install the boot loader somewhere, probably `/dev/sda1`.

**Comment by venya-san** [comment]
**Ubuntu 20.04 LTS**
i experience same error too while changing background.jpg with **Grub Customizer**. 


this is the error when i try to set .png files:
```
error: can't find command 'hwmatch'.
error: jpeg: invalid jpeg file.

press any key to continue...
```

this is the error when i try to set .jpg files:
```
error: can't find command 'hwmatch'.
error: invalid argument.

press any key to continue...

```

**Comment by vinceliuice** [comment]
If you want change the background, don't use this tool, just replace the jpg file

**Comment by vinceliuice** [comment]
Then run sudo update-grub

**Comment by venya-san** [comment]
i try a few times... it's not working. but if i restore the original **background.jpg** the image is loaded and the error didn't show up. seems like i can't change the wallpaper for now.

**Comment by venya-san** [comment]
btw i use your old theme (?) i can the image by installing this theme from here:
`https://drive.google.com/open?id=0B1tVpdpC9bZDLWxKVHBMQWRXU0U`

source:http://ubuntuhandbook.org/index.php/2017/06/vimix-grub2-theme-makes-ubuntu-boot-loader-look-prettier/

**Comment by nullmax** [comment]
I forget to mention that I run into this problem because I changed the backgroud image.
I tried to replace the picture before installation and replace the picture in /usr/share/grub/themes/Tela after installation. But all failed with the same error: can't find hwmatch.
Is it the problem of my own jpg file?

**Comment by vinceliuice** [comment]
Maybe,  grub not support all type pictures

**Comment by venya-san** [comment]
thanks #70 i just open this now i think @vinceliuice didn't fix this problem, will update the theme right now see if it really fixed.

**Comment by venya-san** [comment]
thanks @VergeDX i just open this now i think @vinceliuice will not fix this problem and i will update the theme right now see if the problem really fixed.

**Comment by venya-san** [comment]
thanks @VergeDX i just open this now i think @vinceliuice don't want to fix this problem and i will update the theme right now see if the problem really fixed.

**Comment by venya-san** [comment]
I can change the image... you dont have to overwrite background.jpg
open boot/grub/themes/Tela (if you dont have Tela folder you maybe install the other theme) add another file for example background.png and open theme.txt change
-dekstop:image: "background.jpg" to -dekstop:image: "background.png"  
And... done! the next restart you background will change.

**Comment by venya-san** [comment]
I can change the background on boot... you dont have to overwrite background.jpg
open boot/grub/themes/Tela (if you dont have Tela folder you maybe install the other theme) add another file for example background.png and open theme.txt change
-dekstop:image: "background.jpg" to -dekstop:image: "background.png"  
And... done! the next restart you background will change.

**Comment by Dragon8oy** [comment]
Is this issue sorted or still present? If it's fixed it can be probably be closed, otherwise I'll try look into it.

**Comment by azusaairi** [comment]
It's fixed... at least for me. Idk for other people.

**Comment by azusaairi** [comment]
Sorry I use other acc... TvT
