### ISSUE TITLE
How to change icon from Ubuntu to Mint

### ISSUE THREAD

**Issue by Mal752** [vinceliuice/grub2-themes#71]
Hi, I have installed the Tela theme and I have Windows, Arch and Mint 18.3. The icon for Mint is shown as Ubuntu. How can I change the icon to Mint?

Thank you.

**Comment by vasyl-haievyi** [comment]
I had to add ```--class linuxmint``` for corresponding entry in my grub.cfg file.
It is located in ```/boot/grub``` and entry now starts like this :
```
menuentry 'Linux Mint 18.3 Cinnamon 64-bit' --class linuxmint --class ubuntu --class gnu-linux --class gnu 
```
You may also want to add ```--class``` option to others entries, like memtest or others available entry icons.
Info [here](https://unix.stackexchange.com/questions/163985/whats-the-purpose-of-the-class-option-in-grubs-menuentry) and [here](https://www.gnome-look.org/p/1200710/)

**Comment by Mal752** [comment]
Thank you for the help! Followed the advice and now all good. Thank you again!
