### ISSUE TITLE
New Icons: 60+ new (and upgraded) icons in colour and black-and-white

### ISSUE THREAD

**Issue by Tabaluga** [vinceliuice/grub2-themes#75]
Dear @vinceliuice  ,

last week I found a collection of great icons that I want to share with you, so you can replace your existing icons with these highly recognized icons and finally expand your collection:

## Flat Round System

- Autor: Aha-Soft
- Style: Glyph, Flat, Smooth
- Icons: 60
- Format: vector (SVG)
- License: [Creative Commons (Attribution 3.0 Unported)](https://creativecommons.org/licenses/by/3.0)
- Weblink: [iconfinder.com/iconsets/flat-round-system](https://iconfinder.com/iconsets/flat-round-system)

To further support you, I have already created a new collection as SVG file containing all icons and attached the file as archive.

## The changes I made were simple but very time consuming

1. added all coloured icons from your collection and replaced them if a newer symbol is available in the collection.
2. added all missing icons from your black-and-whiten and replaced them if a newer symbol is available in the collection.
3. added the icons I created and replaced them if a newer icon is available in the collection.
4. created new action icons based on the Fontawesome collection.
5. added all remaining new icons from your collection.
6. cleaned up all icons: alignment; dimensions; deleted empty points, lines and objects.

## Description of the SVG file

The attached SVG file consists of four layers:

1. layer: These are the main icons in only one colour (white), except the chrome icons.
2. layer: These are the coloured background circles of the icons.
3. layer: The description of the sources including web links.
4. layer: The template for new icons.

With this collection you can create coloured and black-and-white icons and you don't have to edit two files:

1. To create the coloured icons, simply hide layers three and four.
2. To create the black-and-white icons, simply hide layers two, three and four.

Please do not hesitate to contact me if you have any further questions.

best regards

## Screenshot

![20200709_grub2-themes_icons](https://user-images.githubusercontent.com/11356216/87227523-e3f43100-c39b-11ea-9314-e176b3c0fc65.png)

## The SVG collection

[20200709_grub2-themes_icons.zip](https://github.com/vinceliuice/grub2-themes/files/4907022/20200709_grub2-themes_icons.zip)

### Flat Round System: icons collection

- iconfinder_android_386449.svg
- iconfinder_apple_386450.svg
- iconfinder_archlinux_386451.svg
- iconfinder_bada_386452.svg
- iconfinder_blackberry_386453.svg
- iconfinder_centOS_386454.svg
- iconfinder_chakra_386455.svg
- iconfinder_chrome_386457.svg
- iconfinder_chrome_browser_386456.svg
- iconfinder_clearOS_386458.svg
- iconfinder_debian_386459.svg
- iconfinder_fedora_386460.svg
- iconfinder_firefox_386461.svg
- iconfinder_foresight_linux_386462.svg
- iconfinder_freebsd_386464.svg
- iconfinder_freebsd_daemon_386463.svg
- iconfinder_gentoo_386465.svg
- iconfinder_gnome_386466.svg
- iconfinder_gnu_386467.svg
- iconfinder_internet_explorer_386468.svg
- iconfinder_iOS_386469.svg
- iconfinder_java_386470.svg
- iconfinder_kde_386471.svg
- iconfinder_knoppix_386472.svg
- iconfinder_konqueror_386473.svg
- iconfinder_kubuntu_386474.svg
- iconfinder_linux_mint_386475.svg
- iconfinder_linux_tox_386476.svg
- iconfinder_mac_os_386478.svg
- iconfinder_mac_os_X_386477.svg
- iconfinder_mandriva_386479.svg
- iconfinder_microsoft_windows_386480.svg
- iconfinder_netbsd_386481.svg
- iconfinder_openbsd_386482.svg
- iconfinder_opensuse_386483.svg
- iconfinder_opera_386484.svg
- iconfinder_os_2_386485.svg
- iconfinder_pardus_386486.svg
- iconfinder_PCLinuxOS_386487.svg
- iconfinder_qnx_386488.svg
- iconfinder_qt_386489.svg
- iconfinder_raspberry_386490.svg
- iconfinder_reactos_386491.svg
- iconfinder_redhat_386492.svg
- iconfinder_sabayon_386493.svg
- iconfinder_safari_386494.svg
- iconfinder_sidux_386495.svg
- iconfinder_slackware_386496.svg
- iconfinder_slax_386497.svg
- iconfinder_solaris_386498.svg
- iconfinder_sun_microsystems_386499.svg
- iconfinder_symbian_386500.svg
- iconfinder_tizen_386501.svg
- iconfinder_tor_386502.svg
- iconfinder_ubuntu_386503.svg
- iconfinder_vmware_386504.svg
- iconfinder_webOS_386505.svg
- iconfinder_windows_386506.svg
- iconfinder_xen_386507.svg
- iconfinder_xubuntu_386508.svg

### additional icons

- iconfinder_manjaro_4691449.svg
- iconfinder_steam_287646.svg
- iconfinder_tails_4691278.svg

### fontawesome icons

- backspace-solid.svg
- ban-solid.svg
- clipboard-solid.svg
- clock-solid.svg
- cog-solid.svg
- cogs-solid.svg
- edit-solid.svg
- globe-solid.svg
- keyboard-solid.svg
- power-off-solid.svg
- question-solid.svg
- redo-alt-solid.svg
- search-solid.svg
- sync-alt-solid.svg
- times-circle-solid.svg
- tools-solid.svg
- undo-alt-solid.svg

**Comment by Dragon8oy** [comment]
Isn't the generic Linux icon missing colour in the coloured version?

**Comment by Tabaluga** [comment]
Hallo @Dragon8oy ,

I think the *generic Linux icon* is the fourth icon from the left in the fifth row.

In the collection the colours of all icons were already reduced to the colour white, so that they have the same character as the template of @vinceliuice, except the Chrome icon (third icon from left, second row).

Please do not hesitate to contact me if you have any further questions.

best regards

**Comment by Dragon8oy** [comment]
Ah, okay that makes sense

**Comment by vinceliuice** [comment]
Thank you!

**Comment by itsmordecai** [comment]
@vinceliuice I actually would recommend this since I use Pop! OS and the current icon collection lacks its icon. If not, then I'd request an addition of the Pop! OS icon in the current icon collection.

**Comment by agnivo007** [comment]
Please add MX linux icon, it's among top distros nowadays...

**Comment by Dragon8oy** [comment]
This will probably need to be updated with a Pop! OS icon, as I submitted a pull request for one. Whether or not you make a new one, find one or use the one I just created, it's not up to me. :)

**Comment by Tabaluga** [comment]
Dear @Dragon8oy ,

please excuse my late reply.

After several icons were added and merged, I believe this issue can be closed.

Please do not hesitate to contact me if you have any further questions.

Thank you very much.

Best regards
