### ISSUE TITLE
Pop! OS Icon Not Available

### ISSUE THREAD

**Issue by itsmordecai** [vinceliuice/grub2-themes#76]
In the GRUB theme, the Pop! OS icon is not available instead it uses the default GNU/Linux icon. Would request an addition of the icon for the OS.

**Comment by agnivo007** [comment]
Please add MX linux icon, it's among top distros nowadays...

**Comment by vinceliuice** [comment]
No problem!

**Comment by Dragon8oy** [comment]
I'll work on this in a minute, @agnivo007, if you create a separate issue for this I'll work on that too

**Comment by awtrimpe** [comment]
I am on Pop 20.10 and can only get the Pop icon to show up when I add ``` class pop-os``` to _/boot/grub/grub.cfg_. There are two other classes present, ```class pop``` and ```class os```, but not a class concatenated with the dash

**Comment by Dragon8oy** [comment]
No problem I'll fix this when I get to my computer.
