### ISSUE TITLE
Can we add a small png of our distro?

### ISSUE THREAD

**Issue by erikdubois** [vinceliuice/grub2-themes#8]

**Comment by erikdubois** [comment]
I created one with 32x32 as dimensions
https://github.com/arcolinux/arcolinux-logo/blob/master/arcolinux-logo/arcolinux-32x32.png

**Comment by erikdubois** [comment]
It works here when the lsb_release is arcolinux.
But it should also work on arcolinuxd and arcolinuxb.

**Comment by vinceliuice** [comment]
No problem!

**Comment by arcolinuxz** [comment]
thanks - the link of the image is up there.

**Comment by arcolinuxz** [comment]
There may be a miscommunication here.
Can you add the ArcoLinux logo to this github please?

**Comment by vinceliuice** [comment]
I add it now, you can try again

**Comment by arcolinuxz** [comment]
Hi Vince,
It works great but do you mind adding 2 more icons?

I have seen the icons do **not** show on our ArcoLinuxB and ArcoLinuxD iso's.
cp arcolinux.png arcolinuxb.png
cp arcolinux.png arcolinuxd.png
will do the trick.
Thanks in advance

**Comment by vinceliuice** [comment]
You can check the --class name at your /boot/grub/grub.cfg, because grub theme icons use grub.cfg class name for icon name
![2019-02-11 11-10-29](https://user-images.githubusercontent.com/7604295/52544774-eee51380-2ded-11e9-9047-47cc4266cd2b.png)

**Comment by arcolinuxz** [comment]
I know how to fix it.
I have added 
arcolinuxb.png
and
arcolinuxd.png
Would you be so kind as to add them to your github?

**Comment by vinceliuice** [comment]
Now! it's ok
