### ISSUE TITLE
suggestion - new feature : change delay value on boot

### ISSUE THREAD

**Issue by nicolas2k** [vinceliuice/grub2-themes#81]
Hi!

I'd like to add ton install with a new feature : possibility to change delay value on boot (5 seconds instead 30 seconds in default).

Thanks

**Comment by Krantz-XRF** [comment]
AFAIK, this has nothing to do with a GRUB **theme**, but rather the GRUB **configuration**.

**Comment by nicolas2k** [comment]
I'm not sure, because grub configurator does not effet to change, and I must modify install.sh script to 5 secondes instead 30 secondes

**Comment by Dragon8oy** [comment]
This can be changed in the grub config, and a grub theme doesn't feel like a great place to start configuring grub in that way. If you want to change this, set `GRUB_TIMEOUT` in `/etc/default/grub` to `GRUB_TIMEOUT=30`, and then update grub with the method your distro uses.

**Comment by Dragon8oy** [comment]
You mentioned it doesn't effect the change unless you run install script. My best guess is that you didn't update grub afterwards which makes config changes actually take effect. For Ubuntu, the command is `sudo update-grub`.

**Comment by Dragon8oy** [comment]
@vinceliuice I can add an argument that handles this if you want, but I don't really think it fits here. What do you think?

**Comment by vinceliuice** [comment]
I also think it's not fits here

**Comment by nicolas2k** [comment]
it's all ok, maybe just a notice ...

Thanks
