### ISSUE TITLE
[Request] Include KDE neon and Regolith Linux icon

### ISSUE THREAD

**Issue by meiuwa** [vinceliuice/grub2-themes#83]
Just wanted to have a [KDE neon](https://neon.kde.org) and [Regolith](https://regolith-linux.org) icon in the theme. That's all. Many thanks 🙂

**Comment by vinceliuice** [comment]
No problem!

**Comment by Dragon8oy** [comment]
Is anyone working on this? If no-one is, I'll do it and submit a PR.
:)

**Comment by Dragon8oy** [comment]
I've got the icons ready, but I don't know what classes they use for grub. I asked on a forum, but if anyone here knows I can make a pull request.

**Comment by Dragon8oy** [comment]
This should be closed by #103
Regolith uses the same GRUB class as Ubuntu, so if you want to use Regolith, you can replace `assets/assets-color/icons-RESOLUTION/ubuntu.png` with `assets/assets-color/icons-RESOLUTION/regolith.png`, where RESOLUTION is either 1080p, 2k or 4k
The other option is to modify your `/boot/grub/grub.cfg` and change each `--class ubuntu` to `--class regolith`. This can also be done by a shell script, in `/etc/grub.d/`, but I don't know enough about how it works to write one.
