### ISSUE TITLE
Custom Background-Image

### ISSUE THREAD

**Issue by Anagastes** [vinceliuice/grub2-themes#85]
Cannot replace the background image.

To make it easy for me, I replaced the background image in the Slaze-Theme and then installed it.

However, the image does not load, as soon as I use the original, it will be loaded correctly in grub2.

What is the reason for this?

**Comment by vinceliuice** [comment]
In theory, as long as you use the same file name `background.jpg` and resolution, it'll work for all `jpg` pictures

**Comment by Anagastes** [comment]
> In theory, as long as you use the same file name `background.jpg` and resolution, it'll work for all `jpg` pictures

Okay, so I can't find the mistake.
Then it must be the picture.

I have exported it with Gimp as RGB and suitable 1920x1080 with 8Bit.
This is probably the error. Is there a recommendation, which program provides suitable results for grub2?

PS: PNG and TGA did not work either.

**Comment by Dragon8oy** [comment]
I used a solid grey background, exported from GIMP 2.10 as a jpg, and it worked fine. As long as the file is named correctly and in the right place, then grub is refreshed with whatever method your distro uses, I don't see why this shouldn't work?

**Comment by Anagastes** [comment]
> I used a solid grey background, exported from GIMP 2.10 as a jpg, and it worked fine. As long as the file is named correctly and in the right place, then grub is refreshed with whatever method your distro uses, I don't see why this shouldn't work?

Okay, I just can't find a fault.

As soon as I change the image in the theme, nothing more of the theme will work.

Here are 2 GIFs and a picture how I change it. Arch/Manjaro is used and Plymouth. 


1.slaze-work "https://streamable.com/n68dhi"
2.change-background.jpg
3.Background-changed "https://streamable.com/7o3jlo"

**Comment by Dragon8oy** [comment]
Did you update grub after changing the background? It seems to me liie grub can't find the background so doesn't load the theme. Tou said you're on arch, so the command should be:
`grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by Anagastes** [comment]
Yeah I do.

The update-grub command is just a script which runs the grub-mkconfig tool to generate a grub.cfg file. It follows exactly this command.

**Comment by Dragon8oy** [comment]
What's the output when it's run? For me, it detects the theme and mentions it, so if it's silent it might be missing the theme somehow.

**Comment by Anagastes** [comment]
What do you mean by that exactly?

The theme is detected during the update, exactly. But as soon as I change the image in the theme with one of mine, the update is successful (theme is found) but no theme is loaded on boot.

**Comment by Dragon8oy** [comment]
Sorry I'm not great at explaining, I was trying to figure out if a different background was somehow causing GRUB to not find the theme anymore, but it still finds it, so it's not that. I'm sorry I can't help much more, I don't know enough about GRUB.

**Comment by Dragon8oy** [comment]
Can you try the `custom-background` branch of `https://github.com/Dragon8oy/grub2-themes` and follow these following instructions:
 - Make sure your custom background matches your resolution
 - Place your custom background inside the root of the project, and name it either background.jpg or custom-background.jpg
 - Run the installer like normal, but with `--custom-background` as an extra argument

**Comment by Anagastes** [comment]
Thanks for your interest and commitment. 

If I follow the readme exactly, I get the same error.

And your variable seems not to be built in yet. :)

```bash
./install.sh --slaze --custom-background
  
 ERROR: Unrecognized installation option '--custom-background'. 
  Try './install.sh --help' for more information.
```

**Comment by Dragon8oy** [comment]
The README on that branch is incorrect, the documentation for it is in the `readme-rewrite` branch. Did you definitely clone the `custom-background` branch of my fork? I can't reproduce this issue on my machine.

**Comment by Dragon8oy** [comment]
Okay, you can actually use the `master` branch of this repo, both pull requests with the documentation and the change were merged.

**Comment by Anagastes** [comment]
All right.

And yes, I'm sure. As a test now without background. The variable is not recognized. :) 

Here you can see it.
https://streamable.com/ph86o7

**Comment by Dragon8oy** [comment]
The right command should've been `git clone -b custom-background https://github.com/Dragon8oy/grub2-themes.git`, but I've deleted that branch now it's been merged into this repo. Can you try again with `git clone https://github.com/vinceliuice/grub2-themes.git` please? Sorry if I wasn't clear earlier :)

**Comment by Anagastes** [comment]
Sorry, my mistake. :) 
The variable now works.

But again I have a simple grub2 menu with a custom image.

Slowly I doubt my sanity, if it works for you. :D

It must be the image. If I just change the background images you provide (stylish background for slaze) it works o.o 

Can you trigger the error with this image?

![custom-background](https://user-images.githubusercontent.com/17494592/96336425-f8715500-107f-11eb-970b-5cc494f5c8f9.jpg)

**Comment by vinceliuice** [comment]
@Anagastes Use the gThumb open it then Delete Metadate

**Comment by Dragon8oy** [comment]
Using that image I get the same issue, and gThumb didn't fix it.

**Comment by Anagastes** [comment]
Okay. Then it's definitely the picture.

Deleting the metadata, didn't help me either. 

I have exported the picture again with "8Bit" "300DPI" etc.

What else could be the reason for this?

**Comment by vinceliuice** [comment]
@Dragon8oy Sorry it's the Rotate Physically, I click the Delete Metadate and Rotate Physically both, then it works , so I'm not sure which is the effective step

**Comment by vinceliuice** [comment]
![1702957734](https://user-images.githubusercontent.com/7604295/96337334-f8da1200-10b8-11eb-8ddc-07316eed90d3.jpg)

**Comment by Dragon8oy** [comment]
I can't test right now, but if this works I'll add documentation for this issue to the README

**Comment by Anagastes** [comment]
Now the picture works.

I am probably predestined for mistakes. The icons are no longer loaded. Sorry if I'm a bit annoying with it. 🥺

![IMG_20201017_124020587](https://user-images.githubusercontent.com/17494592/96337455-97e61600-1087-11eb-980f-36030eccb6f9.jpg)

**Comment by vinceliuice** [comment]
I fixed this issue on my repositorie, you can try my version

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/grub2-themes/commit/091dc940a9da48f760c41e9885b04091cc94485b

**Comment by Anagastes** [comment]
I can confirm it, it is fixed.

Thanks a thousand for your patience, time and great work!  😁

**Comment by vinceliuice** [comment]
You are welcome!

**Comment by Dragon8oy** [comment]
Can the part where metadata is stripped, and whatever the `Rotate Physically` option does, be automated or scripted? If so, it won't need to be added to the README, and instead can be added to the install script.

**Comment by vinceliuice** [comment]
I ran `gthumb --help-all` but did not get any option related to `Rotate Physically`

**Comment by Anagastes** [comment]
Maybe this will help? There are probably some CLI tools that could. :)

https://photo.stackexchange.com/questions/91560/how-can-i-physically-rotate-a-digital-photo-under-linux

**Comment by vinceliuice** [comment]
Maybe this is a good solution

**Comment by Dragon8oy** [comment]
Can `optipng -strip all background.jpg` be used to strip the metadata? Then `convert -auto-orient background.jpg background.jpg` might work to rotate the image, unless I misunderstood.

**Comment by Anagastes** [comment]
> Can `optipng -strip all background.jpg` be used to strip the metadata? Then `convert -auto-orient background.jpg background.jpg` might work to rotate the image, unless I misunderstood.

optipng didnt support jpg.

exiftool -all= IMAGE.JPG should work to remove meta

**Comment by vinceliuice** [comment]
I tested, there is no need to Delete Metadate, only the `Rotate Physically` is the effective step

**Comment by Dragon8oy** [comment]
> optipng didnt support jpg.

I should've seen that coming, ha ha
If someone can test `convert -auto-orient background.jpg`, I'll add the dependency to the README, and add it into the script.

**Comment by Anagastes** [comment]
I have tested it successfully.

```bash
convert <input file> -strip <output file>
convert -auto-orient background.jpg background.jpg
```

**Comment by vinceliuice** [comment]
Yes it works!

**Comment by vinceliuice** [comment]
I updated the install.sh

**Comment by Dragon8oy** [comment]
Your commit won't work if the background is called custom-background.jpg
The line should be `convert -auto-orient "${THEME_DIR}/${name}/${custom_background}" "${THEME_DIR}/${name}/${custom_background}"`

**Comment by vinceliuice** [comment]
Isn't that the copied file will be renamed to background.jpg?

**Comment by Dragon8oy** [comment]
Ah yes, sorry I thought you were modifying the file before it's installed, I missed that you were modifying the installed file. :)

**Comment by Dragon8oy** [comment]
@Anagastes Does the install script work for you completely now?

**Comment by Anagastes** [comment]
> @Anagastes Does the install script work for you completely now?

Yes, it now works with every picture :)

**Comment by Dragon8oy** [comment]
Can this issue be closed then? I'm glad the issue was fixed :)

**Comment by Anagastes** [comment]
> Can this issue be closed then? I'm glad the issue was fixed :)

Sure :)

Thank you! 😎🤩
