### ISSUE TITLE
Confusing REAME.md

### ISSUE THREAD

**Issue by Dragon8oy** [vinceliuice/grub2-themes#87]
Hi, the README formatting feels a little off, and I also think more information could be added, including custom backgrounds and manually setting icons. Some of the wording is also a little confusing.

I'll work on this myself, unless you don't want this, otherwise I'll probably have a pull request ready in a few days.

**Comment by Dragon8oy** [comment]
Guidelines for how to contribute could also be added, this might hopefully reduce the number of people asking for icons to be added, and instead encourage them to help out.

**Comment by vinceliuice** [comment]
That will be great! thanks so much!
